services:
  mariadb:
    image: bitnami/mariadb:latest
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=CAMBIA_ROOT_DB
      - MARIADB_DATABASE=wordpress
      - MARIADB_USER=wp_user
      - MARIADB_PASSWORD=CAMBIA_DB_PASS
    volumes:
      - wp_mariadb_data:/bitnami/mariadb

  wordpress:
    image: bitnami/wordpress:latest
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_NAME=wordpress
      - WORDPRESS_DATABASE_USER=wp_user
      - WORDPRESS_DATABASE_PASSWORD=CAMBIA_DB_PASS
      - WORDPRESS_BLOG_NAME=Mi WordPress
      - WORDPRESS_USERNAME=admin
      - WORDPRESS_PASSWORD=CAMBIA_ADMIN_PASS
      - WORDPRESS_EMAIL=tu-correo@dominio.com
      - WORDPRESS_ENABLE_REVERSE_PROXY=yes
      - WORDPRESS_ENABLE_HTTPS=yes
    volumes:
      - wordpress_data:/bitnami/wordpress

volumes:
  wp_mariadb_data:
  wordpress_data:
